from django.db import models
from django.contrib.auth.models import AbstractUser

from framework.utils.cornflakes.decorators import model_config


@model_config()
class User(AbstractUser):
    # id of the user, generated by cornflakes
    id = models.AutoField(primary_key=True, null=False)
    # email to communicate with the user
    email = models.EmailField(unique=True, null=False, blank=False)

    # boolean, whether email address is verified
    isEmailVerified = models.BooleanField(default=False)
    # varchar(255), stores user's first name
    first_name = models.CharField(max_length=255, default='', blank=True, verbose_name='First Name')
    # varchar(255), stores user's last name
    last_name = models.CharField(max_length=255, default='', blank=True, verbose_name='Last Name')


__all__ = [
    'User',
]

